version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   commit-message:
  #     prefix: "chore"
  #     include: "scope"
  #   reviewers:
  #     - "ReturnFI"
  #   labels:
  #     - "dependencies"
  #     - "github_actions"
